file_format: "1"
id: vua
name: VUA
url: https://github.com/Deemen17
type: shield
arch: arm
requires: [pro_micro]
features:
  - keys
  - display
outputs:
  - usb
  - ble
siblings:
  - vua_dongle
  - vua_left
  - vua_right
